// Create a new HTML structure to insert
const newHtmlStructure = document.createElement('div')
newHtmlStructure.innerHTML = `
<span id="hs_cos_wrapper_widget_1653941807042_" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text" style="" data-hs-cos-general-type="widget" data-hs-cos-type="rich_text"><header>
<p style="text-align: center;"><strong><span style="text-decoration: underline;">MODERN HEALTH SOFTWARE AS A SERVICE TERMS OF USE</span></strong></p>
<p style="text-align: justify;">Last updated:<span style="background-color: #ffffff;"> <strong>29 June 2022</strong></span></p>
<p style="text-align: justify;">These Modern Health Software as a Service Terms of Use (the “<strong>Terms of Use</strong>”) form an agreement between Modern Health Canada Inc. (“<strong>Modern Health</strong>”, “<strong>us</strong>”, “<strong>we</strong>”, “<strong>our</strong>”) and you, and are entered into the earlier of: (a) the date you first use any part of the Modern Health SaaS Services; and (b) the date you agree to be bound by these Terms of Use (the “<strong>Effective Date</strong>”). The term “you” refers to the person browsing, accessing or otherwise using the Modern Health SaaS Services (“<strong>use</strong>” or “<strong>using</strong>” in these Terms of Use will mean any of the foregoing).&nbsp;</p>
<p style="text-align: justify;">These Terms of Use govern your use of the services through which we host and make available the Modern Health solution for the administration, management and coordination of health, coaching and wellness services (“<strong>Modern Health SaaS Services</strong>”).&nbsp; Modern Health makes its Modern Health SaaS Services available to mental health professionals, mental health clinics or other similar organizations (each, a “<strong>Modern Health Customer</strong>”), which enables Modern Health Customers to engage with their patients or clients directly (each, a “<strong>Client</strong>”).&nbsp;</p>
<p style="text-align: justify;">THE MODERN HEALTH SAAS SERVICES SHOULD NOT BE USED IF YOU ARE EXPERIENCING A MEDICAL EMERGENCY. IF YOU HAVE A MEDICAL EMERGENCY, YOU SHOULD CALL 911 IMMEDIATELY OR ATTEND THE EMERGENCY ROOM OF THE NEAREST HOSPITAL.</p>
<p style="text-align: justify;">Modern Health is a technology company and our role is limited to providing the Modern Health Saas Services to our Modern Health Customers (operating at arm’s length to Modern Health) and making available the list of our Modern Health Customers to individuals who are seeking the services of a mental health professional.&nbsp; We are not a health care provider, do not engage any health care providers, and are not engaged in the practice of psychology, psychotherapy, social work or any other health profession.&nbsp; Modern Health is not a party to any therapist-patient relationship that may be established through the Modern Health SaaS Services.&nbsp; We are not liable for any health services provided to you, which are provided by the applicable Modern Health Customer and not by Modern Health.&nbsp; The inclusion of any Modern Health Customer on any directory or listing maintained by Modern Health should not be considered an endorsement, representation or warranty regarding the safety, appropriateness or effectiveness of any particular Modern Health Customer, treatment or service.</p>
<p style="text-align: justify;">If you are issued a user account to the Modern Health SaaS Services by, or are otherwise using the Modern Health SaaS Services on behalf of a Modern Health Customer that has separately entered into an agreement with us to subscribe to the Modern Health SaaS Services (a “<strong>Customer Agreement</strong>”), you acknowledge that the applicable Customer Agreement governs the relationship between Modern Health and the Modern Health Customer and includes certain requirements that will apply to you.</p>
<p style="text-align: justify;"><strong>By using the Modern Health SaaS Services, you: (a) represent and warrant that (i) you have the capacity to enter into binding obligations, and (ii) all information supplied by you to us through the Modern Health SaaS Services is true, accurate, current and complete; and (b) agree to be bound by and comply with these Terms of Use, as updated from time to time in accordance with Section</strong> <strong>1</strong>.<strong> If you do not agree to these Terms of Use, you must not use the Modern Health SaaS Services.</strong> <strong>If you are using the Modern Health SaaS Services on behalf of another person, you hereby represent and warrant to Modern Health that you have the authority to bind such person to these Terms of Use.</strong></p>
<ol>
<li style="list-style-type: none;">
<ol> <li aria-level="1" style="list-style-type: decimal;"><strong>Changes to these Terms of Use and the Modern Health SaaS Services</strong>
<ol style="list-style-type: lower-alpha;">
<li aria-level="2">Except where prohibited by applicable law, we reserve the right to change these Terms of Use at any time by posting a new version to our website at<strong> <a href="//practicespace.health/?hsLang=en">http://practicespace.health/</a></strong><strong>&nbsp;</strong>(the “<strong>Website</strong>”). It is your obligation to monitor the Modern Health SaaS Services for any such changes. Your continued access to or use of the Modern Health SaaS Services after any changes to these Terms of Use indicates your acceptance of such changes. It is your responsibility to review these Terms of Use regularly.&nbsp;</li>
<li aria-level="2">We reserve the right to change the Modern Health SaaS Services at any time, without notice.</li>
</ol>
</li>
<li aria-level="2" style="list-style-type: decimal;"><strong>Modern Health SaaS Services</strong>
<ol style="list-style-type: lower-alpha;">
<li aria-level="2"><span style="text-decoration: underline;">Right to Use. </span>Subject to your compliance with the terms and conditions of these Terms of Use, Modern Health will make the Modern Health SaaS Services available to you on the terms and conditions set out in these Terms of Use.</li>
<li aria-level="2"><span style="text-decoration: underline;">Restrictions on Use. </span>You will not use the Modern Health SaaS Services in violation of these Terms of Use or of any applicable law. Without limiting the generality of the foregoing, you will not (and will not attempt to) directly or indirectly:&nbsp;
<ol style="list-style-type: lower-roman;">
<li aria-level="2">send, upload, collect, transmit, store, use, post, publish, or otherwise communicate on the Modern Health SaaS Services any data, information, content, records, or files that: (i) contains any computer viruses, worms, malicious code, or any software intended to damage or alter a computer system or data; (ii) you do not have the lawful right to send, upload, collect, transmit, store, use, post, publish, or otherwise communicate; (iii) infringes, violates or otherwise misappropriates the intellectual property or other rights of any third party (including without limitation any moral right, privacy right or right of publicity); (iv) is false, intentionally misleading, or impersonates any other person; (v) is bullying, harassing, abusive, threatening, vulgar, obscene, or offensive, that contains pornography, nudity, or graphic or gratuitous violence, or that promotes violence, racism, discrimination, bigotry, hatred, or physical harm of any kind against any group or individual; (vi) is harmful to minors in any way or targeted at minors; or (vii) encourages any conduct that may violate any applicable laws or would give rise to civil or criminal liability;</li>
<li aria-level="2">share, transfer or otherwise provide access to an account designated for you to another person;</li>
<li aria-level="2">disable, overly burden, impair, or otherwise interfere with servers or networks connected to the Modern Health SaaS Services (e.g., a denial of service attack);</li>
<li aria-level="2">attempt to gain unauthorized access to the Modern Health SaaS Services;</li>
<li aria-level="2">use any data mining, robots, or similar data gathering or extraction methods, or copy, modify, reverse engineer, reverse assemble, disassemble, or decompile the Modern Health SaaS Services or any part thereof or otherwise attempt to discover any source code;&nbsp;</li>
<li aria-level="2">use the Modern Health SaaS Services for the purpose of building a similar or competitive product or service; or</li>
<li aria-level="2">authorize, permit, enable, induce or encourage any third party to do the above.&nbsp;</li>
</ol>
<br><br></li>
<li><span style="text-decoration: underline;">Suspension of Access; Scheduled Downtime</span>. Modern Health may, at its discretion, suspend your access to or use of the Modern Health SaaS Services or any component thereof:&nbsp;
<ol style="list-style-type: lower-roman;">
<li aria-level="2">for scheduled maintenance;</li>
<li aria-level="2">if you violate any provision of these Terms of Use;&nbsp;</li>
<li aria-level="2">to address any emergency security concerns; or&nbsp;</li>
<li aria-level="2">if required to do so by a regulatory body or as a result of a change in applicable law.</li>
</ol>
</li>
</ol>
<br><br></li>
<li aria-level="2" style="list-style-type: decimal;"><strong>Ownership; Reservation of Rights</strong>
<ol style="list-style-type: lower-alpha;">
<li aria-level="2">You retain all ownership and intellectual property rights in and to any content or information that you submit to the Modern Health SaaS Services. You grant to Modern Health a nonexclusive, worldwide, royalty-free, sublicensable, fully paid-up right during the Term to use, process, store, disclose and transmit such data: (i) for the purposes of making the Modern Health SaaS Services available to you (including without limitation to improve and enhance the Modern Health SaaS Services and for other development, diagnostic and corrective purposes in connection with the Modern Health SaaS Services); (ii) as otherwise expressly provided in these Terms of Use (including, for certainty, as described in the Privacy Policy) and (iii) to produce data, information or other materials that are not identified as relating to a particular individual or company (such data, information and materials, “<strong>Aggregated Data</strong>”). We may use, process, store, disclose and transmit the Aggregated Data for any purpose and without restriction or obligation to you of any kind.<strong>&nbsp;</strong></li>
<li aria-level="2">We (or our licensors) retain all ownership and intellectual property rights in and to: (i) the Modern Health SaaS Services; (ii) anything developed or delivered by us or on our behalf under these Terms of Use; and (iii) any modifications, improvements, customizations, updates, enhancements, aggregations, compilations, derivative works, translations and adaptations to the foregoing (i) and (ii).</li>
<li aria-level="2">The Modern Health SaaS Services and all materials developed or delivered by us or on our behalf hereunder are made available or licensed and not “sold” to you. All rights not expressly granted by us to you under these Terms of Use are reserved.</li>
</ol>
<br><br></li>
<li aria-level="2" style="list-style-type: decimal;"><strong>Privacy; Warranty&nbsp;&nbsp;</strong>
<ol style="list-style-type: lower-alpha;">
<li aria-level="2">Please review our current privacy policy, available at <a href="https://www.practicespace.health/privacy-policy?hsLang=en">https://www.practicespace.health/privacy-policy</a>&nbsp;(the “<strong>Privacy Policy</strong>”), which contains important information about our practices in collecting, storing, using and disclosing information about identifiable individuals (“<strong>Personal Information</strong>”), and which is hereby incorporated into and forms a part of these Terms of Use.</li>
<li aria-level="2">You represent and warrant that any data, information, records and files that you load, transmit to or enter into the Modern Health SaaS Services will only contain Personal Information in respect of which you have provided all necessary notices and disclosures, obtained all applicable third party consents and permissions and otherwise have all authority, in each case as required by applicable law, to enable us to make available on the Modern Health SaaS Services.&nbsp;&nbsp;<br><br></li>
</ol>
</li> <li aria-level="2" class="decimal"><strong>User Accounts</strong>
<ol style="list-style-type: lower-alpha;">
<li aria-level="2">To access certain features of the Modern Health SaaS Services, you may be required to successfully sign up for a user account using the available interfaces of the Modern Health SaaS Services and be issued with or create, as applicable, a username and password login credentials (the “<strong>User ID</strong>”). If you are issued with or create a User ID, you will keep your User ID secure and will not share your User ID with anyone else. You are solely responsible for any and all use of your user account and all activities that occur under or in connection with your user account. We reserve the right to disable any User ID at any time in our sole discretion. If we disable access to your User ID, you may be prevented from accessing the Modern Health SaaS Services.<strong>&nbsp;</strong></li>
<li aria-level="2">You agree to: (i) use reasonable efforts to prevent unauthorized access to or use of the Modern Health SaaS Services; (ii) monitor and control all activity conducted through your account in connection with the Modern Health SaaS Services; and (iii) promptly notify us if you become aware of or reasonably suspect any illegal or unauthorized activity or a security breach involving your account, including any loss, theft, or unauthorized disclosure or use of a User ID or account information.<br><br></li>
</ol>
</li>
<li aria-level="2" class="decimal"><strong>Third Party Content, Websites or Services</strong><br>The Modern Health SaaS Services may provide links or access to third party content, websites, or services. Likewise, we may allow you to access the Modern Health SaaS Services from third party systems. Modern Health does not endorse any third party content, websites, services, or systems, or guarantee their quality, accuracy, reliability, completeness, currency, timeliness, non-infringement, merchantability, or fitness for any purpose. Third party content, websites, services, or systems are not under Modern Health’s control, and if you choose to access any such content, websites, or services, or to access the Modern Health SaaS Services from such systems, you do so entirely at your own risk. You acknowledge that you may be required to accept terms of use applicable to third party content, websites, services, or systems and agree to accept and comply with any such terms of use.<br><br></li>
<li aria-level="2" class="decimal"><strong>Payment Processors</strong><br>The collection, processing, and clearance of payments for any services provided to you by Modern Health Customers, and distribution of funds to Modern Health Customers, will be performed by our third party payment processor (the “<strong style="font-size: 1rem; text-align: justify; background-color: transparent;">Payment Processor</strong><span style="font-size: 1rem; text-align: justify; background-color: transparent;">”) and will be subject to the terms, conditions and privacy policies, if any, of the Payment Processor in addition to these Terms of Use. We are not responsible for any error by, or other acts or omissions of, the Payment Processor(s). Our current Payment Processor is Stripe. For more information on Stripe and to review Stripe’s terms and conditions, please visit Stripe’s website: https://stripe.com/. We may use additional Payment Processors, as identified by us from time to time on the Website.&nbsp;</span></li>
<li aria-level="2" class="decimal"><strong>Malicious Code and Security</strong>
<ol style="list-style-type: lower-alpha;">
<li aria-level="2">The downloading and viewing of content are done at your own risk. We do not guarantee or warrant that the Modern Health SaaS Services are compatible with your computer system or that the Modern Health SaaS Services, or any links from the Modern Health SaaS Services, will be free of viruses, worms, trojan horses or disabling devices or other code that manifests contaminating or destructive properties. You are responsible for implementing safeguards to protect the security and integrity of your computer system, and you are responsible for the entire cost of any service, repairs or connections of and to your computer system that may be necessary as a result of your use of the Modern Health SaaS Services.</li>
<li aria-level="2">You are prohibited from violating or attempting to circumvent the security of the Modern Health SaaS Services, including without limitation: (i) accessing content that is not intended for you; (ii) attempting to breach or breaching Modern Health SaaS Services security or authentication measures; (iii) restricting, disrupting or disabling service to Modern Health SaaS Services users, hosts, servers or networks by any means; or (iv) otherwise attempting to interfere with the proper working of the Modern Health SaaS Services, including but not limited to by introducing any material that is malicious or technologically harmful.<br><br></li>
</ol>
</li>
<li aria-level="2" class="decimal"><strong>Communications Not Confidential</strong><br>We do not guarantee the confidentiality of any communications made by you through the Modern Health SaaS Services. We do not guarantee the security of data transmitted over the Internet or public networks in connection with your use of the Modern Health SaaS Services.<br><br></li>
<li aria-level="2" class="decimal"><strong>General Disclaimer</strong><br>THE LAWS OF CERTAIN JURISDICTIONS, INCLUDING QUEBEC, DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LEGAL WARRANTIES, CONDITIONS OR REPRESENTATIONS. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE FOLLOWING EXCLUSIONS OR LIMITATIONS MAY NOT APPLY AND YOU MAY HAVE ADDITIONAL RIGHTS.&nbsp;
<ol style="list-style-type: lower-alpha;">
<li aria-level="2">YOU ACKNOWLEDGE, UNDERSTAND, AND AGREE THAT THE MODERN HEALTH SAAS SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE”, WITH ALL FAULTS AND WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WE DISCLAIM ANY AND ALL REPRESENTATIONS, WARRANTIES AND CONDITIONS OF ANY KIND WITH RESPECT TO THE MODERN HEALTH SAAS SERVICES WHETHER EXPRESS, IMPLIED, STATUTORY OR COLLATERAL, INCLUDING, WITHOUT LIMITATION, THE IMPLIED REPRESENTATIONS, WARRANTIES AND CONDITIONS OF MERCHANTABILITY, MERCHANTABLE QUALITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, OR ANY WARRANTIES OR CONDITIONS ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE, OR THAT THE MODERN HEALTH SAAS SERVICES ARE OR WILL BE ERROR-FREE OR WILL OPERATE WITHOUT INTERRUPTION. YOU ARE SOLELY RESPONSIBLE FOR DETERMINING THE SUITABILITY OF THE MODERN HEALTH SAAS SERVICES.</li>
<li aria-level="2">YOU ACKNOWLEDGE AND AGREE THAT NO HEALTH SERVICE IS PROVIDED BY MODERN HEALTH, MODERN HEALTH IS NOT A PARTY TO ANY THERAPIST-PATIENT RELATIONSHIP THAT MAY BE ESTABLISHED THROUGH THE MODERN HEALTH SAAS SERVICES, AND ANY HEALTH SERVICE OR MENTAL HEALTH TREATMENT ACCESSED THROUGH THE MODERN HEALTH SAAS SERVICE WILL BE&nbsp; PROVIDED BY A MODERN HEALTH CUSTOMER, ALL OF WHICH ARE ARM’S LENGTH THIRD PARTIES, OPERATING COMPLETELY INDEPENDENTLY OF MODERN HEALTH. MODERN HEALTH HAS NO RESPONSIBILITY OR OVERSIGHT REGARDING ANY FEES OR CHARGES THAT MODERN HEALTH CUSTOMER’S CHARGE FOR THEIR HEALTH SERVICES.&nbsp; IN NO CIRCUMSTANCE IS MODERN HEALTH RESPONSIBLE FOR ANY ASPECT OF A HEALTH SERVICE.&nbsp;<br><br></li>
</ol>
</li>
<li aria-level="2"><strong>Additional Client Disclaimers</strong><br>THE LAWS OF CERTAIN JURISDICTIONS, INCLUDING QUEBEC, DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LEGAL WARRANTIES, CONDITIONS OR REPRESENTATIONS. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE FOLLOWING EXCLUSIONS OR LIMITATIONS MAY NOT APPLY AND YOU MAY HAVE ADDITIONAL RIGHTS.&nbsp;
<ol style="list-style-type: lower-alpha;">
<li aria-level="2"><strong><span style="text-decoration: underline;">Medical Disclaimer.</span></strong><strong> You acknowledge and agree that the Modern Health SaaS Services consist of a technology and administrative platform only that is not designed or intended to constitute a recommendation or endorsement of any health care provider (including any Modern Health Customer), substitute for professional health referral, medical advice, diagnosis or treatment and should not be used as a replacement or substitute for professional health referrals, medical advice, diagnosis, treatment or judgment.</strong></li> <li aria-level="2"><strong style="font-size: 1rem; text-align: var(--bs-body-text-align); background-color: transparent;"><span style="text-decoration: underline;">Health Services</span></strong><strong style="font-size: 1rem; text-align: var(--bs-body-text-align); background-color: transparent;">. All of the providers who deliver healthcare services through the Modern Health SaaS Services are operating at arm’s length to Modern Health and are independent professionals who are solely responsible for such services. You acknowledge and agree that Modern Health does not provide medical or health triaging, advice, diagnosis, or treatment, and is strictly a technology platform and infrastructure for Modern Health Customers, who are independent third party providers, including mental health professionals, to connect with their patients and clients. You acknowledge and agree that any healthcare provider using the Modern Health SaaS Services are solely responsible for and will have complete authority, responsibility, supervision, and control over the provision of all health services, advice, instructions, treatment decisions, and other professional health care services performed, and that all diagnoses, treatments, procedures, and other health care services are provided and performed exclusively by or under the supervision of providers, in their sole discretion, as they deem appropriate. </strong></li>
<li aria-level="2"><strong style="font-size: 1rem; text-align: var(--bs-body-text-align); background-color: transparent;"><span style="text-decoration: underline;">Technical Limitations</span></strong><strong style="font-size: 1rem; text-align: var(--bs-body-text-align); background-color: transparent;">. As with any health-related service, there are potential risks associated with the use of the Modern Health SaaS Services to access your health-related service. These risks include, but may not be limited to, the following: </strong>
<ol style="list-style-type: lower-roman;">
<li aria-level="2"><strong style="font-size: 1rem; text-align: var(--bs-body-text-align); background-color: transparent;">the availability, responsiveness or competence of any Modern Health Customer, including whether any Modern Health Customer will continue to make their services available to clients through the Modern Health SaaS Services or comply with their ethical and professional duties, standards of care or applicable law;</strong></li>
<li aria-level="2"><strong>information transmitted may not be sufficient (e.g., poor resolution of images or video quality) to allow for appropriate health care decision making by the health professional using the Modern Health SaaS Service;</strong></li>
<li aria-level="2"><strong>delays in evaluation or treatment could occur due to failures of the electronic equipment; or</strong></li>
<li aria-level="2"><strong>security protocols could fail, causing a breach of privacy of personal health information.</strong></li>
</ol>
</li>
</ol>
</li>
<li aria-level="2"><strong>Indemnification</strong><br>You will defend, indemnify and hold harmless Modern Health, our affiliates and service providers, and each of their and our respective employees, officers, directors, affiliates, agents, contractors, successors, and assigns from and against any and all claims (including without limitation causes of action, damages, recoveries, losses, deficiencies, interest, penalties, reasonable legal fees or other costs or expenses of any kind or nature), directly or indirectly arising from or in connection with:&nbsp;
<ol style="list-style-type: lower-alpha;">
<li aria-level="2">any content or information that you submit to the Modern Health SaaS Services;</li>
<li aria-level="2">your breach of any provision of these Terms of Use or any documents referenced herein;</li>
<li aria-level="2">your violation of any law or the rights of a third party (including without limitation intellectual property rights); or</li>
<li aria-level="2">your use, or the use by any third party using your User ID, of the Modern Health SaaS Services.<br><br></li>
</ol>
</li>
<li aria-level="2"><strong>Limitation of Liabilities</strong><br>THE LAWS OF CERTAIN JURISDICTIONS, INCLUDING QUEBEC, DO NOT ALLOW THE LIMITATION OF LIABILITY OR CERTAIN DAMAGES. IF THESE LAWS APPLY YOU, SOME OR ALL OF THE BELOW LIMITATIONS MAY NOT APPLY AND YOU MAY HAVE ADDITIONAL RIGHTS.
<ol style="list-style-type: lower-alpha;">
<li aria-level="2">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL MODERN HEALTH BE LIABLE, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY OR PUNITIVE DAMAGES; OR FOR ANY LOST SAVINGS, PROFIT, DATA, USE, OR GOODWILL, PERSONAL INJURY OR DEATH, PERSONAL OR PROPERTY DAMAGE, OR FINES, FEES, PENALTIES OR OTHER LIABILITIES, IN EACH CASE, WHETHER OR NOT WE WERE NOTIFIED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES, RESULTING FROM OR RELATED TO THE MODERN HEALTH SAAS SERVICES OR THESE TERMS OF USE.<strong>&nbsp;&nbsp;</strong></li>
<li aria-level="2">FOR ANY OTHER DAMAGES, OR TO THE EXTENT THAT THE FOREGOING LIMITATION IS NOT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL OUR TOTAL AGGREGATE LIABILITY IN CONNECTION WITH OR UNDER THESE TERMS OF USE, OR YOUR USE OF, OR INABILITY TO MAKE USE OF, THE MODERN HEALTH SAAS SERVICES, EXCEED <strong>$100 CAD</strong>. FOR GREATER CERTAINTY, THE EXISTENCE OF ONE OR MORE CLAIMS UNDER THESE TERMS OF USE WILL NOT INCREASE THIS MAXIMUM LIABILITY AMOUNT.<br><br></li>
</ol>
</li>
<li aria-level="2"><strong>Term and Termination; Effect of Termination; Survival</strong>
<ol style="list-style-type: lower-alpha;">
<li aria-level="2"><span style="text-decoration: underline;">Term.</span> The Terms of Use will commence on the Effective Date and will continue until terminated in accordance with its terms (the “<strong>Term</strong>”).</li>
<li aria-level="2"><span style="text-decoration: underline;">Termination.</span> If you have been issued a user account as a Modern Health Customer, we may terminate these Terms of Use at any time upon termination of our relationship with the applicable Modern Health Customer.&nbsp; If you are a Client, we may terminate these Terms of Use by providing notice of not less than 30 days to you through the Modern Health SaaS Services.&nbsp; Notwithstanding the foregoing, if your access to Modern Health SaaS Services has been suspended in accordance with these Terms of Use, Modern Health may terminate these Terms of Use at any time.&nbsp; &nbsp; If you are a Client, you may terminate these Terms of Use at any time and with immediate effect by requesting (by email or through any then-available interfaces on the Modern Health SaaS Services) that your User ID be deleted and ceasing use of the Modern Health SaaS Services. For greater certainty, if you continue to use any portion of the Modern Health SaaS Services after these Terms of Use have been terminated, these Terms of Use will continue to apply to the extent of such use.</li>
<li aria-level="2"><span style="text-decoration: underline;">Effect of Suspension or Termination.</span> It is your responsibility to contact the applicable Modern Health Customer to access any applicable health records or to contact your health provider upon the expiration or termination of these Terms of Use.</li>
<li aria-level="2"><span style="text-decoration: underline;">Survival.</span> The following Sections, together with any other provision of these Terms of Use which expressly or by its nature survives termination or expiration, or which contemplates performance or observance subsequent to termination or expiration of these Terms of Use, will survive expiration or termination of these Terms of Use for any reason: Section 2(b) (Restrictions on Use), Sections 3 (Ownership; Reservation of Rights), 4 (Privacy; Warranty), 6 (Third Party Content, Websites or Services), 7 (Payment Processing),&nbsp; 8 (Malicious Code and Security), 9 (Communications Not Confidential), 10 (Disclaimer), 11 (Additional Disclaimer), 12 (Indemnities), 13 (Limitation of Liabilities), 14(d) (Survival), and 16 (General Provisions).&nbsp;<br><br></li>
</ol> </li>
<li aria-level="2"><strong>Geographical Restrictions </strong><br>Modern Health makes no representation that the Modern Health SaaS Services are suitable for use in locations outside Canada. The Modern Health SaaS Services are not intended for use in any jurisdiction where its use is not permitted. If you access the site from outside Canada, you do so at your own risk and you are responsible for compliance with local laws of your jurisdiction. Modern Health makes no representation regarding the licensure or qualifications of any party making services available through the Modern Health SaaS Services in any capacity, including whether such persons are licensed to make services available in your jurisdiction of Canada.<br><br></li>
<li aria-level="2"><strong>General Provisions</strong>
<ol style="list-style-type: lower-alpha;">
<li aria-level="2"><span style="text-decoration: underline;">Assignment.</span> You will not assign these Terms of Use to any third party without our prior written consent. We may assign our rights or obligations under these Terms of Use, in whole or in part, without your consent. Any assignment in violation of this Section will be void. These Terms of Use will enure to the benefit of and be binding upon the parties, their permitted successors and permitted assignees.</li>
<li aria-level="2"><span style="text-decoration: underline;">Choice of Law.</span> Except as restricted by applicable law, these Terms of Use and any action related thereto will be governed by and construed in accordance with the substantive laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflicts of law principles.&nbsp; Such laws apply to your use of the Modern Health SaaS Services, notwithstanding your domicile, residency or physical location. Except as restricted by applicable law, you hereby consent to the exclusive jurisdiction and venue of courts in Toronto, Ontario, Canada in all disputes arising out of or relating to the use of the Modern Health SaaS Services. The U.N. Convention on Contracts for the International Sale of Goods will not apply to these Terms of Use.&nbsp; This choice of jurisdiction does not prevent us from seeking injunctive relief with respect to a violation of intellectual property rights or confidentiality obligations in any appropriate jurisdiction. You will only use the Modern Health SaaS Services in jurisdictions where the Modern Health SaaS Services may lawfully be used.&nbsp;</li>
<li aria-level="2"><span style="text-decoration: underline;">Severability.</span> Any provision of these Terms of Use found by a tribunal or court of competent jurisdiction to be illegal or unenforceable will be severed from these Terms of Use and all other provisions of these Terms of Use will remain in full force and effect.</li>
<li aria-level="2"><span style="text-decoration: underline;">Waiver.</span> Modern Health’s failure to insist upon or enforce strict performance of any provision of these Terms of Use will not be construed as a waiver of any provision or right. A waiver of any provision of these Terms of Use must be in writing and a waiver in one instance will not preclude enforcement of such provision on other occasions.</li>
<li aria-level="2"><span style="text-decoration: underline;">Entire Agreement.</span> These Terms of Use (including, for certainty, the Privacy Policy), together with any applicable Customer Agreement, constitute the entire agreement between you and Modern Health with respect to the subject matter hereof and supersede all prior or contemporaneous agreements, representations or other communications, whether electronic, oral or written, between you and Modern Health with respect to the Modern Health SaaS Services. A printed version of these Terms of Use and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to these Terms of Use to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</li>
<li aria-level="2"><span style="text-decoration: underline;">English Language.</span> It is the express wish of the parties that these Terms of Use and all related documents be drawn up in English. C’est la volonté expresse des parties que la présente convention ainsi que les documents qui s’y rattachent soient rédigés en anglais.</li>
</ol>
</li>
</ol>
</li>
</ol>
<ol>
<li aria-level="1"><strong>Contact Modern Health</strong></li>
</ol>
<p style="text-align: justify;">If you have any questions or comments regarding these Terms of Use, please contact us at <a href="mailto:privacy@practicespace.health" rel="noopener">privacy@practicespace.health</a>.</p>
<p style="text-align: center;"><br><br></p>
</header></span>
 `

// Get the container element by its ID
const container = document.getElementById('termsofuse')

container.appendChild(newHtmlStructure)
